### ISSUE TITLE
what type of code should we add

### ISSUE THREAD

**Issue by Manohar-mj** [MLSC-BSOITR/Books-Collection#247]

**Comment by godmodevegeta** [comment]
I think it's mentioned in the README.md 
Programming books

**Comment by Visha17** [comment]
No need to add any code.U need to add books!!

**Comment by Prajaktalandge** [comment]
In this repository you can add books related to programming, coding concepts, Books related to technology. (refer CONTRIBUTING.md file)
Thankyou.
